---
- name: Install the base configuration
  hosts: frontend
  remote_user: ubuntu
  gather_facts: false

  tasks:
    
    - name: "apt upgrade"
      become: true
      apt:
        upgrade: true
      tags: "install"

    - name: "Install nodejs, npm, gnupg and curl"
      become: true
      apt:
        update_cache: yes
        name: [gnupg, curl, nodejs, npm]
        state: "latest"
      tags: "install"

    - name: Copy the api folder
      ansible.builtin.copy:
        src: ./API
        dest: /home/ubuntu
        mode: "0777"
        force: false

    - name: install api node modules
      ansible.builtin.shell:
        cmd: npm install
        chdir: /home/ubuntu/API

    - name: Copy the api service file
      become: true
      ansible.builtin.copy:
        src: ./services/api.service
        dest: /lib/systemd/system/
        mode: "0777"
        force: true

    - name: Copy the front folder
      ansible.builtin.copy:
        src: ./front
        dest: /home/ubuntu
        mode: "0777"
        force: false

    - name: install front node modules
      ansible.builtin.shell:
        cmd: npm install
        chdir: /home/ubuntu/front

    - name: Copy the front service file
      become: true
      ansible.builtin.copy:
        src: ./services/front.service
        dest: /lib/systemd/system/
        mode: "0777"
        force: true

    - name: Import the public key used by the package management system for mongodb installation 
      ansible.builtin.shell:
        cmd: wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc |  gpg --dearmor | sudo tee /usr/share/keyrings/mongodb.gpg > /dev/null

    - name: Tell to apt where to find mongodb-org repo securely
      ansible.builtin.shell:
        cmd: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

    - name: "Install mongodb-org"
      become: true
      apt:
        update_cache: yes
        name: mongodb-org
        state: present

    - name: Start mongod service unit
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true
        state: started
        name: mongod
      

    - name: Waits for db port
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 27017
    
    - name: Add db user and define role
      ansible.builtin.shell:
        cmd: mongosh localhost:27017 --eval "db = db.getSiblingDB('Linux'); db.createUser({user:'mongoadmin',pwd:'secret',roles:[{role:'readWrite',db:'Linux'}]}); db.keepDbCollection.insert({key:'value'})"
      tags: 'next'

    - name: Add db user and define role
      ansible.builtin.shell:
        cmd: mongosh localhost:27017 --eval "use Linux; "
      tags: 'next'

    - name: Start api service unit
      become: true
      ansible.builtin.systemd_service:
        state: started
        name: api
      tags: 'next'

    - name: Start front service unit
      become: true
      ansible.builtin.systemd_service:
        state: started
        name: front
    